### PR TITLE
Team10 24

### PR DESCRIPTION
**Pull request by tiwdeep464**
added index file and change code

### CODE REVIEW

**Review by amey7198 — APPROVED** [review]
Approvedd buddy!!! good work

**Comment by gbhambale5143** [comment]
Hello Dipak,
  Thank for  new changes

**Review by gbhambale5143 — CHANGES_REQUESTED** [review]
please make som changes

**Comment by tiwdeep464** [comment]
> 
> 
> please make som changes

>>what kind of changes

**Pull request closed without merging**
